service: hello

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
