org: jatwing
app: react-notes
service: react-notes

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: get
          cors: true
    environment:
      STAGE: ${sls:stage}
